name: Deploy to Render

on:
  push:
    branches:
      - main  # or master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # or your preferred version

      - name: Install dependencies
        run: npm install

      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/deploy/srv-csjpgnpu0jms73b452g0 \
          -H "Authorization: Bearer rnd_kG2Ck39ZGxpBs1tD28EWOS0fMYGp"
